database:
  host: localhost
  port: 5432
  username: postgres
  password: password
  name: DATA_STORE
  dataset_prefix: DATASET_
dataset:
  # Configuration of the dataset.
  name: fuel_efficiency
  pandas_args:
    # These parameters need to resemble the arguments that are passed
    # directly to the pandas.read_csv() function.
    filepath_or_buffer: http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data
    names:
      - MPG
      - Cylinders
      - Displacement
      - Horsepower
      - Weight
      - Acceleration
      - Model Year
      - Origin
    na_values: "?"
    comment: "\t"
    sep: " "
    skipinitialspace: true
  preprocessing:
    target_column: MPG
    trainset_ratio: 0.8
    # You can specify custom functions here that should be applied at the raw dataset.
    # They need to be defined in the src.operators.preprocessing.custom_functions.py
    # script. The order here will be kept. 
    custom_functions:
      - drop_missing
      - fuel_efficiency_dummies
