# we only extend the pipeline with a function that drops
# most of the independent variables.
dataset:
  preprocessing:
    name: only_horsepower
    custom_functions:
      - drop_missing
      - fuel_efficiency_dummies
      - keep_horsepower_only
